-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ6OoSOlTKpWeOYXQ
sQWaXavAbL/jMIUdPG/A8kxfK5+gCgYIKoZIzj0DAQehRANCAAQsmTkWqVsxmvor
JsbXTZJKDYEbhjhc1MOmWWV0cji8W6JMTZXqoBwVOdQT24ocUv18sg8Q+3ajb2LC
XkZNqpF+
-----END PRIVATE KEY-----